name: Label Pull Request
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: .github/settings/labeler.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"